### ISSUE TITLE
Send file button does nothing when pressed

### ISSUE THREAD

**Issue by dariusarnold** [DeedleFake/trayscale#104]
With the same environment from #103, I have experienced the following issue in the Trayscale interface:

The button with the text "Send a file to a remote machine" does nothing when pressed. There is no error message. There also is nothing printed in the logs when it is clcked. This is all from the startup:
```
flatpak run dev.deedles.Trayscale
2024/03/22 21:09:44 systray error: failed to request name: org.freedesktop.DBus.Error.ServiceUnknown
2024/03/22 21:09:44 ERROR adw_application_window_set_content: assertion 'gtk_widget_get_parent (content) == NULL' failed glib_old_log_api=1 priority=4 glib_domain=Adwaita
```
Other buttons work for me. I can send files using the tailscale CLI.

**Comment by DeedleFake** [comment]
There's been some trouble with a couple of different buttons recently. I'm not quite sure what caused it. The button for adding an advertised route has disappeared, too.

It _might_ be possible to drag-and-drop the file instead of using the button, but that's been quite buggy and crashes sometimes. I'll look into adding an indicator to show that that's possible.
