### ISSUE TITLE
Provide a Go package for easily writing Tailscale clients

### ISSUE THREAD

**Issue by Jacalz** [DeedleFake/trayscale#129]
It would be nice to have this project provide a package for talking to the Tailscale library easily. This is especially nice to have now that the project no longer relies on the cli.

I suppose one solution would be to expose the tsutil package out of internal/ but having it in a separate module without the GTK deps would also be very useful.

The reason that I'm interested in this is because it would make it a lot easier to write clients for Tailscale. It could potentially also open up for the possibility of more developers working on the backend for this project.

**Comment by DeedleFake** [comment]
`internal/tsutil` is very specific to Trayscale's usecase. I'm not sure how useful it would be outside of this context.

Also, it's in `internal` specifically because I don't want to maintain a public API surface that would then need to have stricter backwards compatibility guarantees than a `cmd` package does. Maybe that could happen one day, but it's definitely not a priority. Sorry.

**Comment by Jacalz** [comment]
Alright. I understand; no worries. Thanks for providing a great application anyhow. I'll just have to communicate using the cli in the meantime for some experiments. Your app solves like 90-95% of what I need to do with Tailscale anyhow so I'll try to suggest improvements and maybe do a PR (can't promise anything due to lack of time though) or two now and again :)
