### ISSUE TITLE
Mullvad duplicate exit-node entries

### ISSUE THREAD

**Issue by aasseman** [DeedleFake/trayscale#141]
The UI for Mullvad exit nodes shows multiple entries for each Mullvad location (probably because there are multiple servers in those locations?).

![image](https://github.com/DeedleFake/trayscale/assets/33075224/90495678-db25-46d1-8ecc-1626f3f4597d)

But tailscale's CLI only shows one entry per Mullvad location, which makes it easier to use:

```
$ tailscale exit-node list

 IP                  HOSTNAME                           COUNTRY            CITY                   STATUS     
 [...]
 100.122.231.14      fr-mrs-wg-001.mullvad.ts.net       France             Any                    -          
 100.114.187.107     fr-bod-wg-002.mullvad.ts.net       France             Bordeaux               -          
 100.122.231.14      fr-mrs-wg-001.mullvad.ts.net       France             Marseille              -          
 100.120.246.19      fr-par-wg-001.mullvad.ts.net       France             Paris                  -          
 100.108.29.93       de-fra-wg-009.mullvad.ts.net       Germany            Any                    -          
 100.123.112.113     de-ber-wg-001.mullvad.ts.net       Germany            Berlin                 -          
 100.78.4.15         de-dus-wg-001.mullvad.ts.net       Germany            Dusseldorf             -          
 100.108.29.93       de-fra-wg-009.mullvad.ts.net       Germany            Frankfurt              -          
 [...]
```

**Comment by DeedleFake** [comment]
Yes, that is because there are multiple servers per location. It doesn't really matter which one you pick, per se, although it does make scrolling through the list a bit awkward. I'll look into changing it to a list of locations, each of which expands to a list of servers in that location. I'll also see if I can add some identifying info for each one of those servers just so you can tell them apart, although it'll probably be something relatively obtuse like their tailnet domain names or something.
