### ISSUE TITLE
KDE Tray Icon

### ISSUE THREAD

**Issue by mfat** [DeedleFake/trayscale#30]
Hi there
Many thanks for this app. KDE still supports tray icon so it would make sense to add support for this. Thanks much.

**Comment by DeedleFake** [comment]
I would if I could, but there isn't a simple way to do it while using Gtk4. Gtk3 has support for tray icons, but you can't use Gtk4 and Gtk3 simultaneously. Trying to do so causes the app to crash. Most of the other libraries out there for handling tray icons actually use Gtk3 behind the scenes, so that doesn't work.

[The Fyne project's](https://github.com/fyne-io/systray), notably, doesn't need Gtk3 and just does the D-Bus work that it needs manually, but it had a lot of problems last I tried it. I can give it another try at some point, perhaps, though. That's probably the best bet.
