### ISSUE TITLE
in kde, trayscale does not have root permission

### ISSUE THREAD

**Issue by csp5me** [DeedleFake/trayscale#56]
if i start trayscale from the kde start menu, it is started without root permission. 

Then the app cannot start/stop tailscale or choose an exit code

**Comment by DeedleFake** [comment]
That is correct and this is expected behavior. The README gives instructions on how to solve this. Essentially, run `sudo tailscale up --operator=$USER` once manually to set up Tailscale to allow your current user to control the daemon. Unfortunately, I haven't come up with a good way around this yet, though a few ideas have been percolating in the back of my head.
